### ISSUE TITLE
Upgrade tippecanoe

### ISSUE THREAD

**Issue by kh-lucgiffon** [nightlark/tippecanoe-pypi#16]
**Is your feature request related to a problem? Please describe.**
Tippecanoe v2.45 seems to contains bugs that create artifacts on my use case. Making it unusable.

**Describe the solution you'd like**
I would like the python-tippecanoe version to be upgraded. v2.56 is good for me.

**Describe alternatives you've considered**
Not using python-tippecanoe but it is more complicated in my case.

**Additional context**
N/A

**Comment by nightlark** [comment]
I’ll get an updated version later today - probably going to be the latest tippecanoe release, v2.72

**Comment by nightlark** [comment]
Wheels for v2.72.0 have been released.
